version: "3"

services:
  client:
    image: client
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api
    container_name: blog-client
    networks:
      - mern-network
  api:
    image: api
    build: ./server
    ports:
      - "8081:8081"
    depends_on:
      - db
    container_name: blog-api
    restart: always
    networks:
      - mern-network
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: blog-db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge